name: release

on:
  workflow_run:
    workflows: ["code quality"]
    types:
      - completed # Trigger this workflow after the CI workflow is completed

permissions:
  contents: read # for checkout

jobs:
  release:
    # Only run if CI workflow was successful and push was to main
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'main' }}
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to publish a GitHub release
      issues: write # to comment on released issues
      pull-requests: write # to comment on released pull requests
      id-token: write # for OIDC for npm provenance
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com/"
          scope: "@${{ github.repository_owner }}"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
